import streamlit as st
import os
import sqlite3
# Note: In a proper environment, you would use a .env file and dotenv library.
# For simplicity in this environment, ensure the GOOGLE_API_KEY is set 
# as a system environment variable, but I'll keep your original structure.
from dotenv import load_dotenv
load_dotenv()

import google.generativeai as genai

# Database file name should be consistent across both files
DB_NAME = "company_data.db" 

# Configure our API key
# Note: Using os.getenv is fine, but in a secure environment, 
# you should handle the missing API key error.
try:
    # We don't need to check for GOOGLE_API_KEY as the runtime handles it, 
    # but we keep the structure for local compatibility.
    api_key = os.getenv("GOOGLE_API_KEY")
    if not api_key:
        st.error("GOOGLE_API_KEY environment variable is not set.")
    genai.configure(api_key=api_key)
except Exception as e:
    st.error(f"Failed to configure Gemini API: {e}. Check your GOOGLE_API_KEY.")


# Function to load Google Gemini model and provide SQL query as response
def get_gemini_response(question, system_prompt):
    """Generates a SQL query using the Gemini API."""
    try:
        model = genai.GenerativeModel('gemini-2.5-flash-preview-05-20')
        
        # FIX: Pass the system prompt and the user question together in the contents list.
        # This method is highly compatible and effectively sets the context/role.
        contents = [
            system_prompt,  # The prompt defining the model's role and schema
            question        # The user's actual question
        ]
        
        response = model.generate_content(
            contents=contents
        )
        return response.text.strip()
    except Exception as e:
        # Simplified error display since the system_instruction issue is addressed.
        st.error(f"Gemini API Error: Could not generate SQL query. Details: {e}")
        return None

# Function to retrieve data from the SQL database
def read_sql_query(sql, db):
    """Executes the SQL query against the database and returns results."""
    conn = None
    try:
        conn = sqlite3.connect(db)
        cur = conn.cursor()
        
        # Execute the SQL query generated by the LLM
        cur.execute(sql)
        rows = cur.fetchall()
        
        # We only commit if the query modifies data (like INSERT/UPDATE/DELETE).
        # conn.commit() 
        return rows
    
    except sqlite3.Error as e:
        # We catch the SQL error and display the problematic query
        st.error(f"SQL Database Error: The generated query failed! Query: {sql}. Error: {e}")
        return []
        
    finally:
        if conn:
            conn.close()


# The detailed prompt context for the LLM
PROMPT_CONTEXT = """
You are an expert in converting English questions to a single, runnable SQL query!
The SQL database has a single table named **employees** and has the following columns:
- **employee_id**: INTEGER (Primary Key)
- **first_name**: TEXT
- **last_name**: TEXT
- **department**: TEXT (e.g., Marketing, Engineering, HR, Sales, Finance)
- **hire_date**: DATE (Format: YYYY-MM-DD)
- **salary**: REAL

Your task is to generate a SQL query based on the user's question.

Example 1 - User Question: How many employees are present in the table?
The SQL command will be something like this **SELECT COUNT(*) FROM employees;**

Example 2 - User Question: Tell me all the employees working in the Engineering department?
The SQL command will be something like this **SELECT * FROM employees WHERE department="Engineering";**

Example 3 - User Question: What is the highest salary paid in the Marketing department?
The SQL command will be something like this **SELECT MAX(salary) FROM employees WHERE department="Marketing";**

IMPORTANT RULE: The SQL code should not have triple quotes (```), backticks, or the word 'sql' in the beginning or end. ONLY provide the raw, executable SQL query string. Do not include any explanatory text.
"""


st.set_page_config(page_title="Text-to-SQL Data Retriever")
st.title("App to Retrieve SQL Data via LLM")

question = st.text_input("Ask a question about the employees table: ", key="input")

submit = st.button("Ask the question")


# If submit is clicked
if submit:
    # Get the raw SQL query from Gemini
    # Pass PROMPT_CONTEXT (the string) directly
    sql_query = get_gemini_response(question, PROMPT_CONTEXT)
    
    if sql_query:
        st.info(f"Generated SQL Query: `{sql_query.strip()}`")
        
        # Retrieve data from the SQL database
        data = read_sql_query(sql_query.strip(), DB_NAME)
        
        st.subheader("Query Result")
        
        if data:
            # Display results using a Streamlit table for better readability
            st.dataframe(data)
        else:
            st.warning("No data returned or an error occurred during query execution.")
